
path: '/content/gdrive/My Drive/Siesta_Sentry Raw Data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: alert
  1: normal
  2: drowsy
