
path: ~/code/ChrisBell193/Siesta_Sentry/raw_data # dataset root dir
train: processed_images/train  # train images (relative to 'path')
val: processed_images/val  # val images (relative to 'path')

# Classes
names:
  0: alert
  1: normal
  2: drowsy
