
path: 'path/to/dataset' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: alert
  1: low_vigilance
  2: drowsy
